// <auto-generated />
using System;
using BotMaster.Telegram.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotMaster.RightsManagement.Migrations
{
    [DbContext(typeof(RightsDbContext))]
    [Migration("20220529171934_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("BotMaster.RightsManagement.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BotMaster.RightsManagement.PlattformUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlattformUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlattformUsers");
                });

            modelBuilder.Entity("BotMaster.RightsManagement.Right", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rights");
                });

            modelBuilder.Entity("BotMaster.RightsManagement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupPlattformUser", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlattformUsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupsId", "PlattformUsersId");

                    b.HasIndex("PlattformUsersId");

                    b.ToTable("GroupPlattformUser");
                });

            modelBuilder.Entity("GroupRight", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupsId", "RightsId");

                    b.HasIndex("RightsId");

                    b.ToTable("GroupRight");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("PlattformUserRight", b =>
                {
                    b.Property<int>("PlattformUsersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlattformUsersId", "RightsId");

                    b.HasIndex("RightsId");

                    b.ToTable("PlattformUserRight");
                });

            modelBuilder.Entity("RightUser", b =>
                {
                    b.Property<int>("RightsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RightsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RightUser");
                });

            modelBuilder.Entity("BotMaster.RightsManagement.PlattformUser", b =>
                {
                    b.HasOne("BotMaster.RightsManagement.User", "User")
                        .WithMany("PlatformIdentities")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupPlattformUser", b =>
                {
                    b.HasOne("BotMaster.RightsManagement.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotMaster.RightsManagement.PlattformUser", null)
                        .WithMany()
                        .HasForeignKey("PlattformUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupRight", b =>
                {
                    b.HasOne("BotMaster.RightsManagement.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotMaster.RightsManagement.Right", null)
                        .WithMany()
                        .HasForeignKey("RightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("BotMaster.RightsManagement.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotMaster.RightsManagement.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlattformUserRight", b =>
                {
                    b.HasOne("BotMaster.RightsManagement.PlattformUser", null)
                        .WithMany()
                        .HasForeignKey("PlattformUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotMaster.RightsManagement.Right", null)
                        .WithMany()
                        .HasForeignKey("RightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RightUser", b =>
                {
                    b.HasOne("BotMaster.RightsManagement.Right", null)
                        .WithMany()
                        .HasForeignKey("RightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotMaster.RightsManagement.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotMaster.RightsManagement.User", b =>
                {
                    b.Navigation("PlatformIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
